Add support of mod filed
bem/bem-sdk pull request #131
Opened 2016-09-18 07:00 UTC by skad0

@tadatuta @zxqfox @blond #95

2016-09-18 08:17 UTC, tadatuta commented
lgtm

2016-09-20 19:01 UTC, zxqfox commented on index.js
> +        var modName = obj.modName || obj.mod;
Если mod это объект, то надо пробовать obj.mod.name

2016-09-20 19:01 UTC, zxqfox commented on index.js
> +            var modVal = obj.modVal || obj.val;
Если mod это объект, то надо пробовать obj.mod.val

2016-09-20 19:02 UTC, zxqfox commented on index.js
> +            if (modVal || modVal === 0 || (!obj.hasOwnProperty('modVal') && !obj.hasOwnProperty('val'))) {
ну опять obj.hasOwnProperty('mod'), наверное

2016-09-20 19:03 UTC, blond commented
Я сильно против таких извращений в `bem-naming`.

2016-09-20 19:04 UTC, qfox requested changes
Кажется, что надо либо отказаться от mod как объекта, либо поддерживать его.

2016-09-21 09:45 UTC, closed without merging