TS: Rewrite bemjson-node
bem/bem-sdk pull request #342
Opened 2018-08-17 14:20 UTC by awinogradov

2018-08-17 15:40 UTC, yarastqt commented on packages/bemjson-node/bemjson-node.ts
> +    public __isBemjsonNode__? = true;
`public __isBemjsonNode__? = true;` — Что за вопросик?

2018-08-17 15:40 UTC, yarastqt commented on packages/bemjson-node/package.json
> +  "main": "bemjson-node",
`bemjson-node.js` или не обязательн тут расширение указывать?

2018-08-17 18:03 UTC, qfox commented on packages/bemjson-node/bemjson-node.ts
> +    public __isBemjsonNode__? = true;
Неуверенный разработчик писал

2018-08-17 18:41 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +        if (options.mix) {
миксы?

2018-08-17 18:41 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +
зачем дыра?

2018-08-17 18:41 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    mix?: IBemJsonNodeOptions | IBemJsonNodeOptions[];
нужно точно?

2018-08-17 18:43 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    public mods: NonStrictMods = {};
Тут более строго должно быть, `Record<string, true | string>`

2018-08-17 18:44 UTC, yarastqt commented on packages/bemjson-node/bemjson-node.ts
> +type NonStrictMods = Record<string, boolean | string | number | undefined>;
Кажется, стоит добавить `export`

2018-08-17 18:44 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +                    : new BemjsonNode(typeof n === 'object' ? n : {block: n})));
Нам точно нужен mix?

2018-08-17 18:44 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    valueOf() {
резать

2018-08-17 18:45 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    toJSON() {
Резать

2018-08-17 18:45 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    toString() {
Резать

2018-08-17 18:45 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    static isBemjsonNode(bemjsonNode: { __isBemjsonNode__?: boolean; [key: string]: any }) {
Думаю, тоже резать

2018-08-17 18:45 UTC, zxqfox commented on packages/bemjson-node/package.json
> +  "main": "bemjson-node",
я бы указал, да

2018-08-17 18:46 UTC, zxqfox commented on packages/bemjson-node/package.json
> +    "cover": "nyc mocha",
`-r ts-node/register`

2018-08-20 09:13 UTC, awinogradov commented on packages/bemjson-node/bemjson-node.ts
> +    toString() {
Тогда у тебя кроме конструктора ничего не останется)

2018-08-20 09:13 UTC, awinogradov commented on packages/bemjson-node/bemjson-node.ts
> +    toString() {
А нам бы классы генерить)

2018-08-20 10:11 UTC, awinogradov commented
```
> const { BemjsonNode } = require('./packages/bemjson-node/bemjson-node.ts')
'use strict'
> const bemjson = new BemjsonNode({ block: 'her', elem: 'tebe', elemMods: { one: 'red' }, mix: { block: 'komu' }})
undefined
> bemjson.toString()
'her__tebe her__tebe_one_red komu'
```

2018-08-20 10:11 UTC, awinogradov commented
@Yeti-or приходи и ты

2018-08-21 18:12 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    naming?: INamingConvention;
но зачем?

2018-08-21 18:13 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +            this.elem = options.elem;
лучше this.elem = options.elem || null;

2018-08-21 18:15 UTC, zxqfox commented on packages/bemjson-node/bemjson-node.ts
> +    toString() {
для классов нужна другая функция
эта херня только контейнер

2018-08-21 18:16 UTC, qfox requested changes
надо обсуждать

2018-10-09 11:42 UTC, closed without merging