Add README for naming.entity.stringify
bem/bem-sdk pull request #353
Opened 2018-11-01 13:26 UTC by migs911

2018-11-15 07:27 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +        elem: '_EL-',
Если тут хочется выделить префксивость, то мб `' EL:'` ?

2018-11-15 17:44 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +        elem: '_EL-',
Да, но `naming.entity.stringify` ведь обычно используют, чтобы сформировать имя класса для CSS, а в имени класса пробелы и двоеточия нельзя. Я следовал этой логике.

Если считаешь важным поправить - ок, могу поправить.

2018-11-16 13:29 UTC, qfox requested changes

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(originNaming);
Почему не `require('@bem/sdk.naming.entity.stringify')(originNaming)`?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +console.log(stringify(entity));
Можно же без console.log ? хотя бы в runkit

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +[RunKit live editor](https://runkit.com/migs911/usage-examples-stringify-bementityname-object).
editor → example?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +When you create stringify function it uses delimeters `INamingConventionDelims` from the naming convention:
Would be nice to see a link to `INamingConventionDelims` definition

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +function stringifyWrapper(convention) {
кажется, что это должно быть ссылкой на код, иначе это воспринимается как пример, который зачем-то надо скопировать в проект

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(convention);
`stringifyWrapper` это алиас для `require('@bem/sdk.naming.entity.stringify')`
Давай использовать саму функцию?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +You can specify a custom naming convention and use it in your stringify function:
in your → to make your?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +| `mod` | `string|object` | (optional) modifier name or object representation of modifier. Object representation has two elements: `name` and `val` (optional). |
`(optional)` twice?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +| `mod` | `string|object` | (optional) modifier name or object representation of modifier. Object representation has two elements: `name` and `val` (optional). |
А точно нам нужно это повторно описывать здесь? Не хватит ссылки на BEMEntityName пакет?

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +Include `@bem/sdk.naming.entity.stringify` package and create stringify function using included preset:
```suggestion
Import `@bem/sdk.naming.entity.stringify` package and create stringify function using `origin` preset:
```

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(originNaming);
```suggestion
const stringify = require('@bem/sdk.naming.entity.stringify')(originNaming);
```

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(originNaming);
```suggestion
const stringify = require('@bem/sdk.naming.entity.stringify')(originNaming);
```

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(originNaming);
```suggestion
const stringify = require('@bem/sdk.naming.entity.stringify')(originNaming);
```

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +[RunKit live editor](https://runkit.com/migs911/usage-examples-stringify-bementityname-object).
```suggestion
[RunKit live example](https://runkit.com/migs911/usage-examples-stringify-bementityname-object).
```

2018-11-16 13:29 UTC, qfox commented on packages/naming.entity.stringify/README.md
> +const stringify = require('@bem/sdk.naming.entity.stringify').stringifyWrapper(convention);
```suggestion
const stringify = require('@bem/sdk.naming.entity.stringify')(convention);
```

2018-11-16 13:30 UTC, zxqfox commented on packages/naming.entity.stringify/README.md
> +        elem: '_EL-',
Не, я не настаиваю

2018-11-19 13:21 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +console.log(stringify(entity));
Убрал все console.log в runkit

2018-11-19 13:26 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +When you create stringify function it uses delimeters `INamingConventionDelims` from the naming convention:
Переформулировал. Сделал ссылку, только на INamingConvention, т.к. передавать надо именно этот объект.

2018-11-19 13:26 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +function stringifyWrapper(convention) {
Переформулировал и добавил ссылку.

2018-11-19 13:30 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +You can specify a custom naming convention and use it in your stringify function:
fixed

2018-11-19 13:30 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +| `mod` | `string|object` | (optional) modifier name or object representation of modifier. Object representation has two elements: `name` and `val` (optional). |
> `(optional)` twice?
fixed

2018-11-19 13:30 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +Include `@bem/sdk.naming.entity.stringify` package and create stringify function using included preset:
везде заменил include на import.

2018-11-19 13:40 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +| `mod` | `string|object` | (optional) modifier name or object representation of modifier. Object representation has two elements: `name` and `val` (optional). |
> А точно нам нужно это повторно описывать здесь? Не хватит ссылки на BEMEntityName пакет?

Надо подумать. @godfreyd  как думаешь, надо ли? Объясню:
В параметрах надо передать объект BemEntityName, но для функции stringify необязательно создавать объект BemEntityName, а можно передать любой объект с элементами `block`, `elem` и `mod`.

Если давать ссылку на BemEntityName, то куда именно?
Есть файлы: packages/entity-name/index.d.ts и packages/entity-name/entity-name.js
Мне кажется, что они оба слишком избыточны для того, кто хочет использовать функцию stringify.

2018-11-19 13:55 UTC, migs911 commented
@zxqfox Обработал все твои комментарии, кроме одного - в нём надо подумать и я призвал  Серёжу.
Все комментарии, которые я поправил и они не требуют повторной проверки (типа "in your → to make your?"), я сразу перевёл в Resolved.

2018-11-21 11:08 UTC, qfox approved these changes

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +    * [Stringify BemEntityName object](#stringify-bementityname-object)
Может уберем вторую вложенность тоже? Кажется, там все на одном экране умещается, а древовидное меню смотрится не очень.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +Stringify returns the string with the name of specified entity representation. This name can be used in a class attributes.
specified entity ... → specified BEM entity ...

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +## Quickstart
Quickstart → Quick start

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +* [Quickstart](#quickstart)
Quickstart → Quick start. В https://github.com/bem/bem-sdk/tree/master/packages/naming.entity.parse тоже исправь.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +1. [Installing required packages](#install-packages).
Installing → Install

Ты просишь пользователя делать действия. Список сделай глаголами. Заголовки оставь такими как есть.

В https://github.com/bem/bem-sdk/tree/master/packages/naming.entity.parse#quickstart тоже поправь.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +3. [Creating a stingify() function](#creating-a-stringify-function).
Creating → Create

Ты просишь пользователя делать действия. Список сделай глаголами. Заголовки оставь такими как есть.

В https://github.com/bem/bem-sdk/tree/master/packages/naming.entity.parse#quickstart тоже поправь.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +4. [Making a string from BEM entity](#stringify-bem-entity).
Making → Make

Ты просишь пользователя делать действия. Список сделай глаголами. Заголовки оставь такими как есть.

В https://github.com/bem/bem-sdk/tree/master/packages/naming.entity.parse#quickstart тоже поправь.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +### Creating a stingify() function
Creating a stingify() function → Creating a `stingify()` function

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +**Examples**: ([RunKit live example](https://runkit.com/migs911/stringify-quickst-using-origin-naming-convention))
- Examples → Example. У тебя по факту один код-блок.
- **RunKit live example** я бы унес в конец примера, а то не понятно, что из этого пример? RunKit или код-блок под ним? Еще плюс избавимся от скобок.
- В https://github.com/bem/bem-sdk/tree/master/packages/naming.entity.parse#parsing-a-string везде тоже поправь, пожалуйста.
- Ссылка [RunKit live example](https://runkit.com/migs911/stringify-quickst-using-origin-naming-convention) — 404.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +// You can define the modifier as an object.
Комментарий // You can define the modifier as an object я бы удалил. Он смещает фокус на себя, а важны стрелочные комментарии. Либо добавлять везде, не понятно, почему в одном месте есть комментарий, а в других нет. Но это будет слишком, кажется.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +You can stringify any object that has required elements, for example [BemEntityName](https://github.com/bem/bem-sdk/tree/master/packages/entity-name) object:
required elements → required elements or modifiers

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +### Stringify BemEntityName object
Не совсем понятно, в чем разница между тем, что было на 70 строчке?

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +This code will print `button_EL-run_MOD-activated` to console.
Почему это словами, а не комментарием, как «До»?

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +**Example:** ([RunKit live example](https://runkit.com/migs911/usage-examples-stringify-bementityname-object))
- **RunKit live example** я бы унес в конец примера, а то не понятно, что из этого пример? RunKit или код-блок под ним? Еще плюс избавимся от скобок.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +
лишняя строка

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +**Example:** ([RunKit live example](https://runkit.com/migs911/stringify-usage-examples-custom-naming-convention))
- **RunKit live example** я бы унес в конец примера, а то не понятно, что из этого пример? RunKit или код-блок под ним? Еще плюс избавимся от скобок.

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +```js
Давай все-таки соблюдать консистентность между документами. В идеале нужно пропустить один пример через весь SDK. В parse ты писал абстрактные примеры:

```
// Parse a block name.
parse('my-block');

// Parse an element name.
parse('my-block__my-element');

// Parse a block modifier name.
parse('my-block_my-modifier');

// Parse a block modifier name with a value.
parse('my-block_my-modifier_some-value');

// Parse an element modifier name.
parse('my-block__my-element_my-modifier');

// Parse an element modifier name with a value.
parse('my-block__my-element_my-modifier_some-value');
```

2018-11-30 09:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +const convention = {
Тоже заведи тикет, на более реалистичный пример, как в parse.

2018-11-30 11:51 UTC, migs911 reviewed
Осталась пара нерешенных комментариев.

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +### Creating a stingify() function
> Creating a stingify() function → Creating a `stingify()` function

Блоки кода в заголовках? Кажется, это не очень красиво.

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +**Examples**: ([RunKit live example](https://runkit.com/migs911/stringify-quickst-using-origin-naming-convention))
> RunKit live example я бы унес в конец примера, а то не понятно, что из этого пример? RunKit или код-блок под ним? Еще плюс избавимся от скобок.

Давай тогда ещё подумаем, как оформить. Вниз убирать не хорошо, т.к. блок кода может быть большим (тут он уже не маленький) и ссылка на RunKit будет внизу, за пределами экрана. Читатель начнет копипастить пример к себе. А возможно, ему хотелось бы открыть его в RunKit.

Примеры бывают ещё больше, бывает что они не помещаются на странице. Поэтому надо сейчас договориться про стиль оформления и делать так везде.

Может ссылку на RunKit писать после слова Example? 
Вот так:
https://github.com/bem/bem-sdk/tree/migelle-naming-doc/packages/naming.entity.stringify#creating-a-string-from-a-bem-entity-name

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +### Stringify BemEntityName object
там просто объект, а тут BemEntityName создаётся. Особой разницы нет, согласен.
Если считаешь, что надо удалить - давай удалю

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +const convention = {
Я сразу такой и завёл =)
DOCAPI-4977: Улучшить пример использования custom naming convention **в stringify** и parse

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +This code will print `button_EL-run_MOD-activated` to console.
исправил

2018-11-30 11:51 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +// You can define the modifier as an object.
Ok

2018-11-30 13:53 UTC, migs911 commented on packages/naming.entity.stringify/README.md
> +You can stringify any object that has required elements, for example [BemEntityName](https://github.com/bem/bem-sdk/tree/master/packages/entity-name) object:
Решили удалить этот пример.

2018-11-30 14:46 UTC, godfreyd commented on packages/naming.entity.stringify/README.md
> +[RunKit live example](https://runkit.com/migs911/stringify-usage-examples-custom-naming-convention)
Точка потерялась.

2018-12-06 11:11 UTC, zxqfox commented on packages/naming.entity.parse/README.md
> + */
зачем так?

2018-12-06 11:51 UTC, godfreyd commented on packages/naming.entity.parse/README.md
> + */
Как? Не понимаю. Имена myBlock, myElement, ...?

2018-12-06 11:53 UTC, godfreyd approved these changes

2018-12-06 12:34 UTC, zxqfox commented on packages/naming.entity.parse/README.md
> + */
`//` заменили на `/*` ;-)

2018-12-07 08:11 UTC, merged