Fix config package README
bem/bem-sdk pull request #381
Opened 2019-01-28 15:19 UTC by godfreyd

2019-01-29 15:36 UTC, tadatuta requested changes

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +* An array of paths to the libraries used.
скорее опций для библиотек и плагинов.

могут быть не только пути и речь не обязательно про require в случае модулей (а плагины — это вообще частный случай, их можно не упоминать), там просто какая-то произвольная конфигурация.

но не путать с плагинами в опциях. там действительно список путей к плагинам, которые подключаются именно к контексте работы конфига.

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +    // Root directory is `/`.
комментарий сбивает с толку. `root: true` — это про то, что не нужно собирать конфиги выше данного по файловой структуре

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +    // Modules and plugins.
плагины не стоит упоминать

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> -    console.log(conf); // config is a merge of CLI args + optionalConfig + all configs found by rc
здесь был полезный комментарий, который в итоге потерялся

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> + *   modules: { 'bem-tools': { plugins: {} } },
кмк, сбивает с толку, т.к. если следовать примеру выше, то здесь окажется конфиг для плагина `create`

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> + * @param {String} [options.name='bem'] - config filename.
тут нужно подробнее: `'bem'` превратится в `.bemrc` и захавает разные варианты (`.bemrc`, `.bemrc.js`, `.bemrc.json`)

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +* [options.fsRoot](#optionsfsroot)
часть опций описана в jsdoc, часть нет

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +Sets the project's root directory. The default value is `/`.
нет, default value выставляется в текущую директорию, не `/`

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +    'levels': {
`levels` можно не брать в кавычки

2019-01-29 15:36 UTC, tadatuta commented on packages/config/README.md
> +const { stripIndent } = require('common-tags');
stripIndent же принципиального значения не имеет, он точно нужен в каждом примере?

да и на счет `mock-fs` в текстовых примерах я не уверен. понятно, что оно нужно для примеров в runkit, но тут, кмк, это лишнее.

2019-01-29 15:51 UTC, godfreyd commented on packages/config/README.md
> +const { stripIndent } = require('common-tags');
Ну, я думал, чтобы скопипастили и заработало. Не хочешь?

2019-01-29 17:25 UTC, migs911 commented on packages/config/README.md
> +const { stripIndent } = require('common-tags');
Сорри, что вмешиваюсь, но можно так:
в RunKit - примеры с mock-fs
а в readme содержмимое файлов в отдельных кодблоках.

Я так сделал в decl. Вот тут в README содержимое файлов в кодблоках:
https://github.com/bem/bem-sdk/tree/feature/readme-decl/packages/decl#loading-declarations-from-files

2019-01-30 06:33 UTC, godfreyd commented on packages/config/README.md
> +* An array of paths to the libraries used.
+

2019-01-30 06:39 UTC, godfreyd commented on packages/config/README.md
> +    // Root directory is `/`.
Поправлю.

2019-01-30 06:40 UTC, godfreyd commented on packages/config/README.md
> +    // Modules and plugins.
Ок

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> -    console.log(conf); // config is a merge of CLI args + optionalConfig + all configs found by rc
Верну. Он немного в другое место перекочевал.

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> + *   modules: { 'bem-tools': { plugins: {} } },
Поправил и упростил.

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> + * @param {String} [options.name='bem'] - config filename.
Поправлю.

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> +* [options.fsRoot](#optionsfsroot)
Ага, спасибо.

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> +const { stripIndent } = require('common-tags');
Ага, давайте тогда так. Для консистентности.

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> +Sets the project's root directory. The default value is `/`.
Удалил

2019-01-30 08:14 UTC, godfreyd commented on packages/config/README.md
> +    'levels': {
Ага.

2019-02-13 14:17 UTC, tadatuta approved these changes

2019-02-13 14:18 UTC, merged